import 'package:flutter/material.dart';

import 'package:sistema_dvolta/paginas/criar_post/post.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: .fromSeed(seedColor: const Color.fromARGB(255, 18, 32, 47))

        
      ), home:const Tela1Login()
    );
  }
}

class Tela1Login extends StatefulWidget {
  const Tela1Login({super.key});

  @override
  State<Tela1Login> createState() => _Tela1Login();
}

class _Tela1Login extends State<Tela1Login> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold (
        body: Column (
      children: [
        Container(
          width: 412,
          height: 914,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              
               Positioned (
                 left: 91,
                 top: 105,
                child: Image.asset("lib/ui/imagens/Logo.png"),
               ),
              Positioned( //borda fina
                left: 58,
                top: 354,
                child: Container(
                  width: 296,
                  height: 378,
                  decoration: ShapeDecoration(
                    color: Colors.white.withValues(alpha: 0),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFBFB9B9),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              
              Positioned(   //botão criar conta
                left: 85,
                top: 651,
                child: Material(
                  color: const Color.fromARGB(255, 255, 255, 255),                  
                  shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF115339),
                      ),
                      borderRadius: BorderRadius.circular(10),
                      ),
                  child: InkWell(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => Post()),
                      );
                    },
                    highlightColor: Colors.transparent,                    
                     child: Container(
                       width: 242,
                       height: 47,                     
                      child: Center(
                      child: Text(
                        'Criar conta',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF115339),
                          fontSize: 28,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 1.40,
                          letterSpacing: -0.56,
                        ),
                      ),
                    ),
                    ),
                  ),
                ),
              ),
             

              Positioned(   //botão de entrar
                left: 85,
                top: 584,
                child: Material(
                  color: const Color(0xFF115339),
                  borderRadius: BorderRadius.circular(10),
                  child: InkWell(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => Post()),
                      );
                    },
                    highlightColor: Colors.transparent,                 
                     child: Container(
                       width: 242,
                       height: 47,                     
                      child: Center(
                      child: Text(
                        'Entrar',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 28,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 1.40,
                          letterSpacing: -0.56,
                        ),
                      ),
                    ),
                    ),                    
                  ),                  
                ),
              ),

              Positioned(
                left: 73,
                top: 380,
                child: SizedBox(
                  width: 80,
                  height: 26,
                  child: Text(
                    'Email',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.40,
                      letterSpacing: -0.40,
                    ),
                  ),
                ),
              ),

              Positioned( // campo de email
                left: 85,
                top: 411,
                child: Material(
                  color: Colors.transparent,
                child: Container(
                  width: 242,
                  height: 50,
                  child: TextFormField(
                  keyboardType: TextInputType.emailAddress,
                  decoration: InputDecoration(
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: const Color(0xFFC0B9B9),
                      ),
                    ),

                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: const Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),

                    errorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),

                    focusedErrorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),

                    hintText: 'ex.: juninho247@gmail.com',
                    prefixIcon: Icon(Icons.email),
                  ),
                  onChanged: (String value) {

                  },
                  validator: (value) {
                    return value!.isEmpty ? 'Por favor digite seu email' : null;
                  },
                ),
                ),
                ),
              ),

              Positioned(
                left: 73,
                top: 482,
                child: SizedBox(
                  width: 80,
                  height: 26,
                  child: Text(
                    'Senha',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.40,
                      letterSpacing: -0.40,
                    ),
                  ),
                ),
              ),

              Positioned( // campo de senha
                left: 85,
                top: 513,
                child: Material(
                  color: Colors.transparent,
                  child: Container(
                    width: 242,
                    height: 50,
                    child: TextFormField(
                    keyboardType: TextInputType.visiblePassword,
                    decoration: InputDecoration(
                      enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: const Color(0xFFC0B9B9),
                      ),
                    ),

                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: const Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),

                    errorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),

                    focusedErrorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),
                      
                      prefixIcon: Icon(Icons.key),

                    
                  ),
                  onChanged: (String value) {

                  },
                  validator: (value) {
                    return value!.isEmpty ? 'Por favor digite uma senha válida' : null;
                  },
                ),
                ),
                ),
              ),
             
              // Positioned(
              //   left: 85,
              //   top: 513,
              //   child: Container( //campo de senha
              //     width: 242,
              //     height: 31,
              //     decoration: ShapeDecoration(
              //       color: Colors.white.withValues(alpha: 0),
              //       shape: RoundedRectangleBorder(
              //         side: BorderSide(
              //           width: 1,
              //           color: const Color(0xFFC0B9B9),
              //         ),
              //         borderRadius: BorderRadius.circular(6),
              //       ),
              //     ),

              //     child:TextFormField(
                   
              //     ),

              //   ),
              // ),

              

              // Positioned( //campo de email
              //   left: 85,
              //   top: 411,
              //   child: Container(
              //     width: 242,
              //     height: 31,
              //     decoration: ShapeDecoration(
              //       color: Colors.white.withValues(alpha: 0),
              //       shape: RoundedRectangleBorder(
              //         side: BorderSide(
              //           width: 1,
              //           color: const Color(0xFFC0B9B9),
              //         ),
              //         borderRadius: BorderRadius.circular(6),
              //       ),
              //     ),
              //   ),
              // ),

              // Positioned(
              //   left: 91,
              //   top: 105,
              //   child: SizedBox(
              //     width: 230,
              //     height: 64,
              //     child: Text.rich(
              //       TextSpan(
              //         children: [
              //           TextSpan(
              //             text: 'D',
              //             style: TextStyle(
              //               color: const Color(0xFFE48D14),
              //               fontSize: 64,
              //               fontFamily: 'Inter',
              //               fontWeight: FontWeight.w600,
              //               height: 1.40,
              //               letterSpacing: -1.28,
              //             ),
              //           ),
              //           TextSpan(
              //             text: 'Volta',
              //             style: TextStyle(
              //               color: const Color(0xFF115339),
              //               fontSize: 64,
              //               fontFamily: 'Inter',
              //               fontWeight: FontWeight.w600,
              //               height: 1.40,
              //               letterSpacing: -1.28,
              //             ),
              //           ),
              //         ],
              //       ),
              //       textAlign: TextAlign.center,
              //     ),
              //   ),
              // ),
            ],
          ),
        ),
      ],
      ),
      ),
    );
  }
}