import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:sistema_dvolta/paginas/home/perfil/editar_informacoes/editar_informacoes.dart';
import 'package:sistema_dvolta/paginas/home/home.dart';
import 'package:sistema_dvolta/paginas/login/cadastro/cadastro.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Supabase.initialize(
    url: 'https://vchcwprpdjrhxyeonwqq.supabase.co',
    publishableKey: 'sb_publishable_JH0-ZIaUMexX6MmZm11OOw_vtKf1K-0',
  );

    runApp(const FigmaToCodeApp());
}

final supabase = Supabase.instance.client;

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: .fromSeed(seedColor: const Color.fromARGB(255, 18, 32, 47))

        
      ), 
      
      home: supabase.auth.currentUser == null ? Tela1Login() : Tela3Feed(),
    );
  }
}

class Tela1Login extends StatefulWidget {
  const Tela1Login({super.key});

  @override
  State<Tela1Login> createState() => _Tela1Login();
}

class _Tela1Login extends State<Tela1Login> {
  final TextEditingController emailController = TextEditingController();
  final TextEditingController senhaController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Container(
        width: double.infinity,
        height: double.infinity,

        decoration: const BoxDecoration(
        image: DecorationImage(
          image: AssetImage('lib/ui/imagens/Fundo.png'),
          fit: BoxFit.cover, 
        ),
      ),

      child: Scaffold (
        backgroundColor: Colors.transparent,
      body: SingleChildScrollView(
        child: Column(
      children: [
        Container(
          width: 412,
          height: 914,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.transparent),
          child: Stack(
            children: [
              
               Positioned (
                 left: 91,
                 top: 105,
                child: Image.asset("lib/ui/imagens/Logo.png"),
               ),
              Positioned( //borda fina
                left: 58,
                top: 354,
                child: Container(
                  width: 296,
                  height: 378,
                  decoration: ShapeDecoration(
                    color: Colors.white.withValues(alpha: 0),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color.fromARGB(255, 240, 232, 213),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              
              Positioned(   //botão criar conta
                left: 85,
                top: 651,
                child: Material(
                  color: const Color.fromARGB(255, 240, 232, 213),                  
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                      ),
                  child: InkWell(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => Tela2Cadastro()),
                      );
                    },
                    highlightColor: Colors.transparent,                    
                     child: SizedBox(
                       width: 242,
                       height: 47,                     
                      child: Center(
                      child: Text(
                        'Criar conta',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color.fromARGB(255, 46, 37, 58),
                          fontSize: 28,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 1.40,
                          letterSpacing: -0.56,
                        ),
                      ),
                    ),
                    ),
                  ),
                ),
              ),
             

              

              Positioned(
                left: 73,
                top: 380,
                child: SizedBox(
                  width: 80,
                  height: 26,
                  child: Text(
                    'Email',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Color.fromARGB(255, 240, 232, 213),
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.40,
                      letterSpacing: -0.40,
                    ),
                  ),
                ),
              ),

              Positioned( // campo de email
                left: 85,
                top: 411,
                child: Material(
                  color: Colors.transparent,
                child: SizedBox(
                  width: 242,
                  height: 50,
                  child: TextFormField(
                    controller: emailController,
                    style: TextStyle(
                      color: Color.fromARGB(255, 240, 232, 213),
                    ),
                    keyboardType: TextInputType.emailAddress,
                    decoration: InputDecoration(
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(20),
                        borderSide: BorderSide(
                          color: const Color.fromARGB(255, 240, 232, 213),
                        ),
                      ),

                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: const Color.fromARGB(255, 80, 61, 104),
                      ),
                    ),

                    errorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),

                    focusedErrorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),

                    hintText: 'ex.: juninho247@gmail.com',
                    hintStyle: TextStyle(
                      color: Color.fromARGB(191, 240, 232, 213),
                    ),
                    prefixIcon: Icon(Icons.email),
                  ),
                  onChanged: (String value) {

                  },
                  validator: (value) {
                    return value!.isEmpty ? 'Por favor digite seu email' : null;
                  },
                ),
                ),
                ),
              ),

              Positioned(
                left: 73,
                top: 482,
                child: SizedBox(
                  width: 80,
                  height: 26,
                  child: Text(
                    'Senha',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      decoration: TextDecoration.none,
                      color: Color.fromARGB(255, 240, 232, 213),
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.40,
                      letterSpacing: -0.40,
                    ),
                  ),
                ),
              ),

              Positioned( // campo de senha
                left: 85,
                top: 513,
                child: Material(
                  color: Colors.transparent,
                  child: SizedBox(
                    width: 242,
                    height: 50,
                    child: TextFormField(
                      controller: senhaController,
                        obscureText: true,
                      style: TextStyle(
                      color: Color.fromARGB(255, 240, 232, 213),
                    ),
                      keyboardType: TextInputType.visiblePassword,
                      decoration: InputDecoration(
                        enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(20),
                        borderSide: BorderSide(
                          color: const Color.fromARGB(255, 240, 232, 213),
                        ),
                      ),

                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: const Color.fromARGB(255, 80, 61, 104),
                      ),
                    ),

                    errorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),

                    focusedErrorBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide(
                        color: Colors.red,
                      ),
                    ),
                      
                      prefixIcon: Icon(Icons.key),

                    
                  ),
                  onChanged: (String value) {

                  },
                  validator: (value) {
                    return value!.isEmpty ? 'Por favor digite uma senha válida' : null;
                  },
                ),
                ),
                ),
              ),

              Positioned(   //botão de entrar
                left: 85,
                top: 584,
                child: Material(
                  color: const Color.fromARGB(255, 240, 232, 213),
                  borderRadius: BorderRadius.circular(10),
                  child: InkWell(
                    onTap: () async {
                      
                       if (emailController.text.isEmpty) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(
                            content: Text("Digite um email"),
                          ),
                        );
                        return;
                      }

                      if (senhaController.text.isEmpty) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(
                            content: Text("Digite uma senha"),
                          ),
                        );
                        return;
                      }

                      try {

                        await supabase.auth.signInWithPassword(
                          email: emailController.text.trim(),
                          password: senhaController.text,
                        );

                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => Tela3Feed(),
                          ),
                        );

                      } catch (e) {

                        print(e);
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(
                            content: Text("Email ou senha incorretos"),
                          ),
                        );

                      }
                    
                    },
                    highlightColor: Colors.transparent,                 
                     child: SizedBox(
                       width: 242,
                       height: 47,                     
                      child: Center(
                      child: Text(
                        'Entrar',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color.fromARGB(255, 46, 37, 58),
                          fontSize: 28,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 1.40,
                          letterSpacing: -0.56,
                        ),
                      ),
                    ),
                    ),                    
                  ),                  
                ),
              ),

              ],
            ),
          ),
        ],
      ),
      ), // esse
      ),
    ),
    );
  }
}